app:
    root-app: true

processor-toolbox:

    processors:

        - type: egg-processor
          name: egg1
        - type: forward-fftw
          name: fft1
        - type: convert-to-power
          name: to-ps1
        - type: egg-processor
          name: egg2
        - type: forward-fftw
          name: fft2
        - type: convert-to-power
          name: to-ps2
        - type: egg-processor
          name: egg3
        - type: forward-fftw
          name: fft3
        - type: convert-to-power
          name: to-ps3
        - type: data-accumulator
          name: acc
        - type: gain-variation
          name: gainvar
        - type: variable-spectrum-discriminator
          name: discrim
        - type: variable-spectrum-discriminator
          name: discrim2
        - type: create-kd-tree
          name: kd-tree
        - type: consensus-thresholding
          name: ct
        - type: dbscan-track-clustering
          name: tr-clust
        - type: hough-transform
          name: hough
        - type: track-proc
          name: tr-proc
        - type: spectrogram-collector
          name: spct-collect
        - type: linear-density-fit
          name: line
        - type: apply-cut
          name: track-cut
        - type: throughput-profiler
          name: profiler
        - type: multi-peak-track-builder
          name: mptb
        - type: multi-peak-event-builder
          name: mpeb
        - type: hdf5-writer
          name: h5w
        - type: root-tree-writer
          name: rootw
        - type: root-spectrogram-writer 
          name: waterfall-writer

    connections:

        #############################
        # First pass: gain variation
        #############################

        # The power spectra are averaged by the data accumulator, and the
        # background power spectrum is modelled by the gain variation
        # processor. The result of the gain variation model is required by 
        # other processors.

        - signal: "egg1:header"
          slot: "fft1:header"

        - signal: "egg1:ts"
          slot: "fft1:ts-fftw"

        - signal: "fft1:fft"
          slot: "to-ps1:fs-fftw-to-psd"

        - signal: "to-ps1:psd"
          slot: "acc:ps"

        - signal: "acc:ps-finished"
          slot: "gainvar:ps"

        - signal: "gainvar:gain-var"
          slot: "discrim:gv"
          order: 0
           
        - signal: "to-ps1:psd"
          slot: "waterfall-writer:psd"
          
        - signal: "egg1:egg-done"
          slot: "waterfall-writer:write-file"
            

        #####################################
        # Second pass: primary track finding
        #####################################

        - signal: "egg2:header"
          slot: "fft2:header"
          order: 0

        - signal: "egg2:header"
#          slot: "h5w:header"
          slot: "rootw:header"
          order: 1

        - signal: "egg2:ts"
          slot: "fft2:ts-fftw"

        - signal: "fft2:fft"
          slot: "to-ps2:fs-fftw-to-psd"

        - signal: "to-ps2:psd"
          slot: "discrim:ps-pre"

        - signal: "discrim:disc-1d"
          slot: "kd-tree:disc-1d"
#          order: 0


#--------------------------------# Write out discrim points?
#--------------------------------# 
#        - signal: "discrim:disc-1d" # to get sparse spectrogram in root
#          slot: "rootw:disc-1d"
#          order: 1 

#        - signal: "discrim:disc-1d" # to get sparse spectrogram in h5
#          slot: "h5w:disc-1d"
#          order: 2

#        - signal: "egg2:egg-done" # write discrim points from buffer
#          slot: "h5w:final-write-points" 
#          order: 0

#        - signal: "ct:kd-tree-out" # consensus thresholding results written to root
#          slot: "rootw:kd-tree"
#          order: 1
#--------------------------------#
#--------------------------------#


        - signal: "egg2:egg-done"
          slot: "kd-tree:make-tree"
#         order: 1

        - signal: "kd-tree:kd-tree"
          slot: "ct:kd-tree-in"

        - signal: "ct:kd-tree-out"
          slot: "tr-clust:kd-tree"
#          order: 0

        - signal: "tr-clust:track"
          slot: "hough:swf-cand"

        - signal: "hough:hough"
          slot: "tr-proc:swfc-and-hough"

        - signal: "tr-proc:track"
          slot: "track-cut:apply"


#--------------------------------# Write out single tracks as well 
#--------------------------------# (before notion of events)?
#        - signal: "track-cut:pass"      
#          slot: "h5w:proc-track"        
#          order: 1

        - signal: "track-cut:pass"      
          slot: "rootw:proc-track"     
          order: 2

#        - signal: "tr-clust:clustering-done"
#          slot: "h5w:final-write-tracks"     
#--------------------------------#
#--------------------------------#


        #####################################
        # Third pass: rotate-and-project
        #####################################

        - signal: "gainvar:gain-var"
          slot: "discrim2:gv"
          order: 1

        - signal: "gainvar:gain-var"
          slot: "line:gv"
          order: 2

        - signal: "track-cut:pass"
          slot: "spct-collect:track"
#          order: 0

        - signal: "egg3:header" 
          slot: "fft3:header"

        - signal: "egg3:ts"
          slot: "fft3:ts-fftw"

        - signal: "fft3:fft"
          slot: "to-ps3:fs-fftw-to-psd"

        - signal: "to-ps3:psd"
          slot: "spct-collect:ps"
        
        - signal: "spct-collect:ps-coll"
          slot: "discrim2:spec-pre"

        - signal: "discrim2:disc-2d"
          slot: "line:thresh-points"

        #####################################
        # Fourth step: Multi-peak grouping
        #####################################
    
        - signal: "line:power-fit"
          slot: "mptb:track"
#          order: 0

#        - signal: "line:power-fit" # writing out results of rotate-project directly as well (to debug)
#          slot: "h5w:power-fit"
#          order: 1

        - signal: "egg3:egg-done"
          slot: "mptb:do-clustering"
#          order: 0

#        - signal: "egg3:egg-done" # writing out results of rotate-project directly as well (to debug)
#          slot: "h5w:final-write-pf"
#          order: 1

        - signal: "mptb:mpt"
          slot: "mpeb:mpt"

        - signal: "mptb:mpt-done"
          slot: "mpeb:do-clustering"

        - signal: "mpeb:event"
#          slot: "h5w:mt-event"
          slot: "h5w:rp-track"
#          order: 0

        - signal: "mpeb:event"
          slot: "rootw:mt-event"
          order: 1

        - signal: "mpeb:events-done"
#          slot: "h5w:final-write-events"
          slot: "h5w:final-write-rp-tracks"

    run-queue:
        - egg1
        - egg2
        - egg3

# PROCESSOR CONFIGURATION

egg1:
    filename: "foo.egg"
    egg-reader: egg3
    number-of-slices: 500          
    slice-size: 8192
    progress-report-interval: 100

fft1:
    transform-flag: ESTIMATE

acc:
    number-to-average: 0       
    signal-interval: 0

gainvar:
    normalize: false
#    min-frequency: 57.5e6 # Evan's setting
#    max-frequency: 142.5e6 # Evan's setting
    min-frequency: 15.0e6
    max-frequency: 185.0e6
    fit-points: 15

egg2:
    filename: "foo.egg"           
    egg-reader: egg3
    number-of-slices: 500           
    slice-size: 8192
    progress-report-interval: 100

egg3:
    filename: "foo.egg"           
    egg-reader: egg3
    number-of-slices: 500
    slice-size: 8192
    progress-report-interval: 100

fft2:
    transform-flag: ESTIMATE

discrim:
    min-frequency: 15.e6
    max-frequency: 185.e6
#    min-frequency: 57.5e6 # Evan's analysis
#    max-frequency: 142.5e6 # Evan's analysis
    snr-threshold-power: 6.0

kd-tree:
    time-radius: 0.0006 
    freq-radius: 0.15e6
    distance-method: euclidean

ct:
    membership-radius: 0.5 
    min-number-votes: 6 

tr-clust:
    min-points: 4 

hough:
    n-theta-points: 100
    n-r-points: 150

tr-proc:
    pl-dist-cut1: 0.07 
    plt-dist-cut2: 0.035 
    min-points: 6 
    min-slope: 1.0
    algorithm: "double-cuts" # this is the default despite the docstring on the processor
#    algorithm: "weighted-slope"
    assigned-error: 12240.

spct-collect:
    min-frequency: 15.e6
    max-frequency: 185.e6
#    min-frequency: 57.5e6 # Evan's analysis
#    max-frequency: 142.5e6 # Evan's analysis
    lead-time: 0.0
    trail-time: 0.0
    lead-freq: 4.e6
    trail-freq: 4.e6
    use-track-freqs: true

discrim2:
    min-frequency: 15.e6
    max-frequency: 185.e6
#    min-frequency: 57.5e6 # Evan's analysis
#    max-frequency: 142.5e6 # Evan's analysis
    snr-threshold-power: 6.0 

line: # see KTLinearDensityProbeFit.hh
    probe-width-small: 50e3 # narrow value of width s of gaussian density for each point
    step-size: 25e3 # increment in intercept sweep
    spectrum-tolerance: 5.0
    spectrum-threshold: 0.4
    algorithm: 2 # rotate-and-project algorithm
    do-density-maximization: false 

track-cut:
    track-cut:

mptb:
    sideband-time-tol: 0.1e-3

mpeb:
    jump-time-tol: 0.25e-3

#h5w:
#    output-file: "foo.h5"
#    file-flag: recreate

rootw:
    output-file: "foo.root"
    file-flag: recreate

waterfall-writer:
    output-file: "katydidwaterfall.root"
    file-flag: recreate
    min-time: 0.0
    max-time: 0.025
    min-freq: 0.0e6
    max-freq: 200.0e6

