name: Build and Test Locust

on: [push]

env:
  locust_mc_BUILD_WITH_KASSIOPEIA: OFF
  locust_mc_ENABLE_EXECUTABLES: ON
  locust_mc_ENABLE_TESTING: ON
  locust_mc_BUILD_TYPE: Debug
  locust_mc_TAG: test

jobs:

  build_cpp:
    name: Build and Test Cpp

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15]

    steps:

      - name: Checkout reposistory
        uses: actions/checkout@feature/Testing
        with:
          submodules: recursive

      - name: Mac Dependencies
        if: startsWith(matrix.os, 'macos')  # Mac only
        run: |
          brew install \
            boost \
            rapidjson \
            yaml-cpp \
            pybind11


      - name: Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')  # Linux only
        run: |
          sudo apt-get update
          sudo apt-get install -yq \
            libboost-all-dev \
            libyaml-cpp-dev \
            rapidjson-dev \
            pybind11-dev 
          pip install "pybind11[global]"
          

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${locust_mc_BUILD_TYPE} -Dlocust_mc_ENABLE_EXECUTABLES=${locust_mc_ENABLE_EXECUTABLES} -Dlocust_mc_ENABLE_TESTING=${locust_mc_ENABLE_TESTING} -Dlocust_mc_BUILD_WITH_KASSIOPEIA=${locust_mc_BUILD_WITH_KASSIOPEIA} ..

      - name: CMake Build
        run: |
          cd build
          make -j install

      - name: Run tests
        run: |
          cd build
          Source/Testing/RunTests


